# Generated by Django 3.2 on 2022-06-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('af', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumiaCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='home/carousel')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'JUMIA CAROUSEL',
            },
        ),
        migrations.CreateModel(
            name='JumiaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='Products')),
                ('url', models.URLField()),
                ('paragraph', models.TextField()),
                ('price', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'JUMIA PRODUCTS',
            },
        ),
        migrations.AlterModelOptions(
            name='homecarousel',
            options={'verbose_name_plural': 'AMAZON CAROUSEL'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'AMAZON PRODUCTS'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
    ]
